In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

In [3]:
# Creating Arrays

In [64]:
list1 = [0,1,2,3,4,5]
list1

[0, 1, 2, 3, 4, 5]

In [65]:
type(list1)

list

In [66]:
arr = np.array(list1)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) # 1st argument should be lesser than 2nd argument

array([], dtype=int32)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-20,15)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14])

In [20]:
np.arange(-25,-15)

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16])

In [21]:
np.arange(20,15)

array([], dtype=int32)

In [23]:
a = np.arange(-20,14)
a

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13])

In [26]:
np.arange(10,10)

array([], dtype=int32)

In [29]:
np.arange(-10,20)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [30]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [31]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [33]:
np.arange(10,30,5,1) # Only three argument required

TypeError: Cannot interpret '1' as a data type

In [35]:
b1 = np.zeros(4) # Parameter tunning
b1

array([0., 0., 0., 0.])

In [37]:
np.zeros(10,dtype = int) # Hyperparameter Tunning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
z = np.zeros((2,4),dtype = int)
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
np.zeros((2,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
np.zeros((15,40),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [53]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n))
print(np.zeros(n1,dtype = int))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [54]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [55]:
np.ones((5,6),dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [56]:
n = (5,8)

In [58]:
np.ones(n,dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [60]:
from numpy import * # internally It will called all 217 functions
arange(5)

array([0, 1, 2, 3, 4])

In [67]:
range(12)
list(range(12))

TypeError: 'list' object is not callable

In [69]:
y = list(range(12))
y

TypeError: 'list' object is not callable

In [70]:
rand(3,2)

NameError: name 'rand' is not defined

In [71]:
random.rand(3,2)

array([[0.56737828, 0.04560015],
       [0.92130949, 0.70711646],
       [0.82421904, 0.78286102]])

In [75]:
np.random.rand(4,3)

array([[0.254149  , 0.52388015, 0.97442598],
       [0.10736625, 0.27926144, 0.14213469],
       [0.77379917, 0.05842092, 0.13674751],
       [0.02654313, 0.69523905, 0.00857686]])

In [76]:
np.rand(10)

AttributeError: module 'numpy' has no attribute 'rand'

In [78]:
np.random.rand(5,7)

array([[0.44307723, 0.19485368, 0.70639633, 0.19174084, 0.55393928,
        0.29607598, 0.40561418],
       [0.00104519, 0.21680128, 0.39722569, 0.28543008, 0.51989422,
        0.46419907, 0.00510528],
       [0.82582206, 0.83496671, 0.01224152, 0.43241367, 0.86374543,
        0.12593645, 0.80804923],
       [0.84162087, 0.00231135, 0.95928199, 0.94675758, 0.81125609,
        0.97306657, 0.8486645 ],
       [0.34822705, 0.39971937, 0.60774997, 0.9771993 , 0.98454329,
        0.26735373, 0.8608328 ]])

In [79]:
np.random.randint(0,10)

1

In [82]:
np.random.randint(0,20,15)

array([18,  2,  2,  4,  0,  6, 16,  7,  4, 16, 13,  7,  3,  5, 19])

In [83]:
np.random.randint(0,100,(10,10))

array([[ 9, 59,  5, 40, 73, 67, 51, 12, 46, 92],
       [52, 60, 72, 49, 69, 88, 72, 31, 67, 96],
       [59, 82, 23, 67, 98, 52, 35, 53, 30, 79],
       [96, 16, 43, 60, 63, 42, 28, 49,  1, 54],
       [99, 17,  4, 12, 77, 19, 73, 57, 45, 69],
       [17,  0, 89, 63, 69, 30, 59, 24, 35, 89],
       [95, 33, 89, 17,  4, 65, 45, 59,  5,  6],
       [38, 47, 33, 61, 30, 37, 76, 86,  0, 35],
       [18,  0, 90, 44, 98, 16, 95, 75, 22, 96],
       [93, 64, 13, 79, 29, 92, 43, 18, 81, 94]])

In [85]:
np.random.randint(50,100,(5,6))

array([[74, 91, 53, 69, 56, 76],
       [67, 82, 80, 50, 67, 82],
       [53, 63, 59, 54, 89, 94],
       [92, 81, 92, 51, 55, 68],
       [93, 72, 84, 90, 79, 69]])

In [87]:
b1 = np.random.randint(10,20,(5,4))
b1

array([[11, 16, 18, 11],
       [15, 19, 12, 10],
       [11, 11, 15, 15],
       [12, 15, 17, 12],
       [19, 11, 12, 14]])

In [89]:
b1[:]

array([[11, 16, 18, 11],
       [15, 19, 12, 10],
       [11, 11, 15, 15],
       [12, 15, 17, 12],
       [19, 11, 12, 14]])

In [91]:
b1[0:2]

array([[11, 16, 18, 11],
       [15, 19, 12, 10]])