# Complete NUMPY DOCUMENTATION



# 1. Array Creation Functions

In [1]:
import numpy as np

In [4]:
# Create an array from a list
a = np.array([1,2,3,4,5])
print("Array a:",a)
print(type(a))

Array a: [1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Create an array with evenly spaced values
b = np.arange(0,10,2) # values from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 2 4 6 8]


In [6]:
# Create an array with linearly spaced values
c = np.linspace(0,1,5) # 5 values evenly spaced between 0 and 1
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [10]:
c1 = np.linspace(1,2,10) # 10 values evenly spaced between 1 and 2
print("Array c:",c1)

Array c: [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [13]:
# Create an array filled with zeros
d = np.zeros((4,5)) # 4 x 5 arrays of zeros
print("Array d:",d)

Array d: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# Create an array filled with ones
Ones = np.ones((4,6),dtype = int)
print("Array ones:\n",Ones)

Array ones:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [19]:
# Create an Identity matrix
I = np.eye(5,dtype = int) # 5 X 5 identity matrix(Diagonal element should be 1)
print("Identity Matrix I:\n",I)

Identity Matrix I :
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# 2. Array Manipulation Functions

In [22]:
# Reshaping an Array
arr = np.array([1,2,3,4,5,6])
reshaped = np.reshape(arr,(2,3))
print("Reshaped Array:\n",reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [28]:
# Flatten an array
f1 = np.array([[1,2,3,4],[5,6,7,8]])
flattened = np.ravel(f1)
print("Flattend array: \n",flattened)

Flattend array: 
 [1 2 3 4 5 6 7 8]


In [31]:
# Transpose an array
T = np.array([[1,2],[3,4],[5,6]])
transposed = np.transpose(T)
print("Array T:\n",T)
print("Transposed Array:\n",transposed)

Array T:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 3 5]
 [2 4 6]]


In [32]:
# Stack array vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Vertical stacked:\n",stacked)

Vertical stacked:
 [[1 2]
 [3 4]]


In [35]:
a3 = np.array([1,2,3,4])
b3 = np.array([5,6,7,8])
stacked = np.hstack([a3,b3])
print("Horizontal stacked:\n",stacked)

Horizontal stacked:
 [1 2 3 4 5 6 7 8]


# 3.Mathematical Functions

In [36]:
# Add two arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

add = np.add(arr1,arr2)
print(add)

[ 6  8 10 12 14]


In [37]:
arr3 = np.array([10,20,30,40])
added = np.add(arr3,5)
print("Added 5 to arr3:",added)

Added 5 to arr3: [15 25 35 45]


In [38]:
# Square of each element
arr3 = np.array([10,20,30,40])
sqr = np.power(arr3,2)
print("Sqaured arr3:\n",sqr)

Sqaured arr3:
 [ 100  400  900 1600]


In [39]:
# Squqre root of each element
arr3 = np.array([10,20,30,40])
squared_root = np.sqrt(arr3)
print("Square root:",squared_root)

Square root: [3.16227766 4.47213595 5.47722558 6.32455532]


In [43]:
# Dot product of two arrays
arr4 = np.array([2,3,4,5])
dot_product = np.dot(arr3,arr4)
print(f"Dot product of {arr3} and {arr4} is:{dot_product}")

Dot product of [10 20 30 40] and [2 3 4 5] is:400


# 4. Statistical Functions

In [46]:
s = np.array([1,2,3,4])
Mean = np.mean(s)
print("Mean of array s is:",Mean)

Mean of array s is: 2.5


In [47]:
# Standard Deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [49]:
# Minimum element of an array
min_element = np.min(arr3)
print(f"Minimum element of array {arr3} is:{min_element}")

Minimum element of array [10 20 30 40] is:10


# 5.Linear Algebra Functions

In [59]:
# Creating a matrix
mat = np.array([[2,5],[4,6]])

In [60]:
# Determinant of a matrix
determinant = np.linalg.det(mat)
print("Determinant of a matrix is",determinant)


Determinant of a matrix is -7.999999999999998


In [62]:
# Inverse of a matrix
inverse = np.linalg.inv(mat)
print("Inverse of matrix:\n",inverse)

Inverse of matrix:
 [[-0.75   0.625]
 [ 0.5   -0.25 ]]


# 6.Random Sampling Functions

In [64]:
# Genereate random values between 0 and 1
random_val = np.random.rand(3)
print("Random values:",random_val)

Random values: [0.81889012 0.15028734 0.55931903]


In [75]:
# Set seed reproducibilty
np.random.seed(0)
# Generate random values between 0 and 1
rand_val = np.random.rand(5)
print("Random values:",rand_val)

Random values: [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [89]:
# Generate random integers
rand_ints = np.random.randint(0,10,size =10)
print("Random integers:",rand_ints)

Random integers: [5 9 8 9 4 3 0 3 5 0]


In [93]:
np.random.seed(0)
rand_ints = np.random.randint(0,10,size =10)
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7 9 3 5 2 4]


# 7. Boolean & Logical Functions

In [101]:
# Check if all elements are True
logical_test = np.array([True,False,False,True])
all_true = np.all(logical_test)
print("Is All elements are True?:",all_true)

Is All elements are True?: False


In [97]:
logical_test = np.array([1,1,1,1,1])
all_true = np.all(logical_test)
print(all_true)

True


In [102]:
logical_test = np.array([0,0,0,0])
all_true = np.all(logical_test)
print(all_true)

False


In [105]:
# Check if any elements is True

logical_test = np.array([False,True,True,False])
any_true = np.any(logical_test)
print(any_true)

True


# Set Operations

In [108]:
# Intersection of two arrays
seta = np.array([1,2,3,4,5])
setb = np.array([4,5,6,7,8])
intersection = np.intersect1d(seta,setb)
print("Intersection of a and b:", intersection) # It will returns the same elements from the 2 set

Intersection of a and b: [4 5]


In [109]:
# Union of two arrays
seta = np.array([1,2,3,4,5])
setb = np.array([4,5,6,7,8])
Union = np.union1d(seta,setb)
print("Intersection of a and b:", Union)

Intersection of a and b: [1 2 3 4 5 6 7 8]


# 9. Array Attribute Functions

In [114]:
# Array atributes
a = np.array([1,2,3])
shape = a.shape
size = a.size
dimensions = a.ndim
dtype = a.dtype

print("Shape of a:",shape)
print("Size of a:",size)
print("dimensions of a:",dimensions)
print("type of a:",dtype)

Shape of a: (3,)
Size of a: 3
dimensions of a: 1
type of a: int32


# 10. Other Functions

In [115]:
# Create a copy of an array
a = np.array([1,2,3,4])
copy_arr = np.copy(a)
print("Coppied array:",copy_arr)

Coppied array: [1 2 3 4]


In [116]:
copy_arr

array([1, 2, 3, 4])

In [118]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes
print(array_size_in_bytes)

16


In [119]:
# Check if two arrays share memory
shared = np.shares_memory(a,copy_arr)
print(shared)

False
