# Day - 1

# NUMPY 
* NumPy(Numerical Python) is a fundamental library for Python numerical computing.
*  It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that require heavy computation.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

In [3]:
import sys
sys.version

'3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# Below code we are converting List to array

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [ ]:
np. # We will only important functiom

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(5.2)

array([0., 1., 2., 3., 4., 5.])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,10) # 1st arg should be < 2nd arg

array([], dtype=int32)

In [18]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
ar = np.arange(-30,10)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [22]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.arange(10,20,5,10) #

TypeError: Cannot interpret '10' as a data type

In [29]:
np.zeros(10,dtype = int) # bydefault it will give float

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Parameter Tunning
* System uses its own parameter is called parameter teunning
# Hyperparameter Tunning
* If user convert 

In [30]:
# 2D arrays
np.zeros((2,2),dtype = int) #By default 2 rows and 2 column

array([[0, 0],
       [0, 0]])

In [32]:
#3D arrays
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.zeros((2,10),dtype  = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
#nD array
np.zeros((10,30),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [38]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [42]:
np.twos((2,3)) # Only zero and ones is inbuild functions

AttributeError: module 'numpy' has no attribute 'twos'

In [43]:
rand(3,2)

NameError: name 'rand' is not defined

In [44]:
random.rand(3,2)

NameError: name 'random' is not defined

In [45]:
np.random.rand(3,2) # np-->package,random--> module, rand --> function

array([[0.52300873, 0.84100639],
       [0.5786714 , 0.26550036],
       [0.54282361, 0.38349643]])

In [50]:
np.random.rand(5)

array([0.18010576, 0.78692422, 0.24897164, 0.37948672, 0.57975174])

In [53]:
np.random.rand(5,2)

array([[0.9166423 , 0.92145938],
       [0.18607368, 0.58837561],
       [0.66722459, 0.39109462],
       [0.7038552 , 0.41129204],
       [0.71622866, 0.31406344]])

In [54]:
np.random.rand(3,5)

array([[0.8029137 , 0.51262032, 0.38617293, 0.53032826, 0.47862914],
       [0.89677568, 0.78121721, 0.32537778, 0.54298835, 0.2602432 ],
       [0.61861698, 0.75131557, 0.60302991, 0.8818343 , 0.763376  ]])

In [58]:
np.random.randint(4,6)

5

In [64]:
np.random.randint(4,10)

7

In [69]:
np.random.randint(2,20,4) # 2nd argument is exclusive

array([13, 15,  2,  2])

In [70]:
np.random.randint(2,20,5)

array([ 2, 15, 13,  4, 17])

In [71]:
np.random.randint(10,20,5)

array([15, 16, 17, 12, 14])

In [73]:
np.random.randint(10,40,(10,5))

array([[37, 38, 30, 36, 28],
       [16, 18, 22, 32, 18],
       [20, 27, 25, 37, 25],
       [14, 31, 34, 21, 11],
       [35, 15, 24, 17, 18],
       [18, 17, 38, 14, 31],
       [39, 24, 35, 19, 11],
       [15, 18, 24, 32, 36],
       [17, 15, 37, 26, 12],
       [15, 30, 35, 13, 15]])

In [75]:
np.random.randint(10,40,(10,10)) 

array([[34, 22, 32, 13, 10, 15, 25, 12, 11, 14],
       [33, 24, 20, 34, 21, 28, 36, 16, 38, 19],
       [35, 22, 19, 21, 35, 38, 12, 34, 20, 33],
       [34, 19, 13, 27, 28, 24, 34, 20, 29, 21],
       [35, 28, 24, 15, 20, 10, 13, 28, 26, 28],
       [11, 32, 18, 34, 13, 34, 17, 12, 13, 16],
       [16, 39, 27, 16, 39, 37, 26, 21, 24, 22],
       [36, 21, 16, 39, 12, 29, 25, 23, 30, 11],
       [22, 35, 20, 34, 37, 38, 33, 29, 28, 27],
       [13, 15, 18, 24, 14, 27, 17, 22, 11, 26]])

In [78]:
np.random.randint(1,100,(12,12)) 

array([[55, 64, 38, 73, 69, 18, 37, 58,  3, 95, 37,  7],
       [ 1, 32, 75, 24, 78, 76, 72, 77, 16, 39, 76, 74],
       [94, 45, 45, 85, 69, 39, 68, 71, 46, 19, 63, 79],
       [38, 34, 84, 36, 35, 88, 37, 72, 17, 88, 71, 62],
       [23, 18, 56, 16, 43, 84, 19, 89, 76, 74, 48,  3],
       [87, 78, 51, 64, 12, 87, 61, 70,  4, 36, 16, 66],
       [97,  9, 20, 19, 95, 13, 77,  6, 17, 83, 23, 65],
       [62, 26, 48,  7, 79, 16, 34, 94, 70, 35, 21, 28],
       [90, 88, 43, 75, 96, 69, 74, 42, 60, 74, 33, 34],
       [73, 12, 52, 16,  7, 26, 38, 27, 53, 66, 12, 56],
       [27, 79, 99, 66, 11, 84, 18, 95, 90, 37, 78, 24],
       [11, 47, 72,  3, 20, 38, 28, 25, 46, 82, 12, 73]])

In [79]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [82]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Slicing in matrix

In [87]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])

In [88]:
type(b)

numpy.ndarray

In [89]:
b

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])

In [90]:
b[:]

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])