# Day - 1

# NUMPY 
* NumPy(Numerical Python) is a fundamental library for Python numerical computing.
* It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that require heavy computation.
* Numpy is a library or packages use to handle multidimensional array

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

In [3]:
import sys
sys.version

'3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# Below code we are converting List to array

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [ ]:
np. # We will only learn important functiom

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(5.2)

array([0., 1., 2., 3., 4., 5.])

In [14]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,10) # 1st arg should be < 2nd arg

array([], dtype=int32)

In [18]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
ar = np.arange(-30,10)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [22]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.arange(10,20,5,10) #

TypeError: Cannot interpret '10' as a data type

In [29]:
np.zeros(10,dtype = int) # bydefault it will give float

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Parameter Tunning
* System uses its own parameter is called parameter teunning
# Hyperparameter Tunning
* If user convert 

In [30]:
# 2D arrays
np.zeros((2,2),dtype = int) #By default 2 rows and 2 column

array([[0, 0],
       [0, 0]])

In [32]:
#3D arrays
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.zeros((2,10),dtype  = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.zeros((10,30),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [38]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [42]:
np.twos((2,3)) # Only zero and ones is inbuild functions

AttributeError: module 'numpy' has no attribute 'twos'

In [43]:
rand(3,2)

NameError: name 'rand' is not defined

In [44]:
random.rand(3,2)

NameError: name 'random' is not defined

In [45]:
np.random.rand(3,2) # np-->package,random--> module, rand --> function

array([[0.52300873, 0.84100639],
       [0.5786714 , 0.26550036],
       [0.54282361, 0.38349643]])

In [50]:
np.random.rand(5)

array([0.18010576, 0.78692422, 0.24897164, 0.37948672, 0.57975174])

In [53]:
np.random.rand(5,2)

array([[0.9166423 , 0.92145938],
       [0.18607368, 0.58837561],
       [0.66722459, 0.39109462],
       [0.7038552 , 0.41129204],
       [0.71622866, 0.31406344]])

In [54]:
np.random.rand(3,5)

array([[0.8029137 , 0.51262032, 0.38617293, 0.53032826, 0.47862914],
       [0.89677568, 0.78121721, 0.32537778, 0.54298835, 0.2602432 ],
       [0.61861698, 0.75131557, 0.60302991, 0.8818343 , 0.763376  ]])

In [58]:
np.random.randint(4,6)

5

In [64]:
np.random.randint(4,10)

7

In [69]:
np.random.randint(2,20,4) # 2nd argument is exclusive

array([13, 15,  2,  2])

In [70]:
np.random.randint(2,20,5)

array([ 2, 15, 13,  4, 17])

In [71]:
np.random.randint(10,20,5)

array([15, 16, 17, 12, 14])

In [73]:
np.random.randint(10,40,(10,5))

array([[37, 38, 30, 36, 28],
       [16, 18, 22, 32, 18],
       [20, 27, 25, 37, 25],
       [14, 31, 34, 21, 11],
       [35, 15, 24, 17, 18],
       [18, 17, 38, 14, 31],
       [39, 24, 35, 19, 11],
       [15, 18, 24, 32, 36],
       [17, 15, 37, 26, 12],
       [15, 30, 35, 13, 15]])

In [75]:
np.random.randint(10,40,(10,10)) 

array([[34, 22, 32, 13, 10, 15, 25, 12, 11, 14],
       [33, 24, 20, 34, 21, 28, 36, 16, 38, 19],
       [35, 22, 19, 21, 35, 38, 12, 34, 20, 33],
       [34, 19, 13, 27, 28, 24, 34, 20, 29, 21],
       [35, 28, 24, 15, 20, 10, 13, 28, 26, 28],
       [11, 32, 18, 34, 13, 34, 17, 12, 13, 16],
       [16, 39, 27, 16, 39, 37, 26, 21, 24, 22],
       [36, 21, 16, 39, 12, 29, 25, 23, 30, 11],
       [22, 35, 20, 34, 37, 38, 33, 29, 28, 27],
       [13, 15, 18, 24, 14, 27, 17, 22, 11, 26]])

In [78]:
np.random.randint(1,100,(12,12)) 

array([[55, 64, 38, 73, 69, 18, 37, 58,  3, 95, 37,  7],
       [ 1, 32, 75, 24, 78, 76, 72, 77, 16, 39, 76, 74],
       [94, 45, 45, 85, 69, 39, 68, 71, 46, 19, 63, 79],
       [38, 34, 84, 36, 35, 88, 37, 72, 17, 88, 71, 62],
       [23, 18, 56, 16, 43, 84, 19, 89, 76, 74, 48,  3],
       [87, 78, 51, 64, 12, 87, 61, 70,  4, 36, 16, 66],
       [97,  9, 20, 19, 95, 13, 77,  6, 17, 83, 23, 65],
       [62, 26, 48,  7, 79, 16, 34, 94, 70, 35, 21, 28],
       [90, 88, 43, 75, 96, 69, 74, 42, 60, 74, 33, 34],
       [73, 12, 52, 16,  7, 26, 38, 27, 53, 66, 12, 56],
       [27, 79, 99, 66, 11, 84, 18, 95, 90, 37, 78, 24],
       [11, 47, 72,  3, 20, 38, 28, 25, 46, 82, 12, 73]])

In [79]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [82]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Day 2

# Slicing in matrix

In [87]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])

In [88]:
type(b)

numpy.ndarray

In [89]:
b

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])

In [90]:
b[:]

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])

In [91]:
# How to print specific rows
b[1:3]

array([[15, 15, 17, 11],
       [10, 13, 15, 15]])

a[2:6]  print the rows (2nd rows till 5th row)
a[2,6] print from the 2nd row print Specific element only

In [93]:
b[1,3]

11

In [94]:
b[1,-1]

11

In [95]:
b[2:3]

array([[10, 13, 15, 15]])

In [96]:
b[0:-2]

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15]])

In [97]:
b[0,2]

17

In [98]:
b

array([[11, 14, 17, 11],
       [15, 15, 17, 11],
       [10, 13, 15, 15],
       [14, 12, 18, 10],
       [19, 16, 18, 17]])

In [99]:
b[-5,-3]

14

In [100]:
b[-5,3]

11

In [101]:
b[-4,2]

17

# Oerations

In [103]:
a = np.random.randint(10,20,10)
a

array([15, 12, 19, 16, 12, 15, 10, 19, 17, 17])

In [105]:
id(a)

1933434858512

In [106]:
__name__

'__main__'

 
In python there are two speacial concept
__name__
__init__

In [107]:
arr 

array([0, 1, 2, 3, 4, 5])

In [108]:
arr2 = np.random.randint(0,100,(10,10))

In [109]:
arr2

array([[79, 90, 36, 17, 80, 29, 93, 51, 44, 28],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64],
       [98, 10, 81, 57, 47, 74, 69, 37, 32, 24],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [82, 70,  4, 55, 24, 83, 30, 42, 24, 76],
       [11, 25, 96, 76,  1, 16, 58, 35, 10, 47],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23],
       [27, 35,  8, 63, 60, 24, 19, 57, 57, 35],
       [56, 96,  4, 70, 29, 93, 41, 31, 38, 79],
       [22, 38,  7, 69, 32,  7, 49, 92, 82, 52]])

In [110]:
arr

array([0, 1, 2, 3, 4, 5])

In [111]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [114]:
arr[0:4]

array([0, 1, 2, 3])

In [115]:
arr2[0:5]

array([[79, 90, 36, 17, 80, 29, 93, 51, 44, 28],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64],
       [98, 10, 81, 57, 47, 74, 69, 37, 32, 24],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [82, 70,  4, 55, 24, 83, 30, 42, 24, 76]])

In [118]:
arr2[1,4]

4

In [119]:
arr2[::-1]

array([[22, 38,  7, 69, 32,  7, 49, 92, 82, 52],
       [56, 96,  4, 70, 29, 93, 41, 31, 38, 79],
       [27, 35,  8, 63, 60, 24, 19, 57, 57, 35],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23],
       [11, 25, 96, 76,  1, 16, 58, 35, 10, 47],
       [82, 70,  4, 55, 24, 83, 30, 42, 24, 76],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [98, 10, 81, 57, 47, 74, 69, 37, 32, 24],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64],
       [79, 90, 36, 17, 80, 29, 93, 51, 44, 28]])

In [120]:
arr2

array([[79, 90, 36, 17, 80, 29, 93, 51, 44, 28],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64],
       [98, 10, 81, 57, 47, 74, 69, 37, 32, 24],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [82, 70,  4, 55, 24, 83, 30, 42, 24, 76],
       [11, 25, 96, 76,  1, 16, 58, 35, 10, 47],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23],
       [27, 35,  8, 63, 60, 24, 19, 57, 57, 35],
       [56, 96,  4, 70, 29, 93, 41, 31, 38, 79],
       [22, 38,  7, 69, 32,  7, 49, 92, 82, 52]])

In [121]:
arr2[::-2]

array([[22, 38,  7, 69, 32,  7, 49, 92, 82, 52],
       [27, 35,  8, 63, 60, 24, 19, 57, 57, 35],
       [11, 25, 96, 76,  1, 16, 58, 35, 10, 47],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64]])

In [122]:
arr2[::-3]

array([[22, 38,  7, 69, 32,  7, 49, 92, 82, 52],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [79, 90, 36, 17, 80, 29, 93, 51, 44, 28]])

In [123]:
arr2[:-3]

array([[79, 90, 36, 17, 80, 29, 93, 51, 44, 28],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64],
       [98, 10, 81, 57, 47, 74, 69, 37, 32, 24],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [82, 70,  4, 55, 24, 83, 30, 42, 24, 76],
       [11, 25, 96, 76,  1, 16, 58, 35, 10, 47],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23]])

In [124]:
arr2

array([[79, 90, 36, 17, 80, 29, 93, 51, 44, 28],
       [30, 33, 93,  0,  4, 63, 24, 65, 55, 64],
       [98, 10, 81, 57, 47, 74, 69, 37, 32, 24],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [82, 70,  4, 55, 24, 83, 30, 42, 24, 76],
       [11, 25, 96, 76,  1, 16, 58, 35, 10, 47],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23],
       [27, 35,  8, 63, 60, 24, 19, 57, 57, 35],
       [56, 96,  4, 70, 29, 93, 41, 31, 38, 79],
       [22, 38,  7, 69, 32,  7, 49, 92, 82, 52]])

In [ ]:
arr2[3:]

In [137]:
arr2[::-3]

array([[22, 38,  7, 69, 32,  7, 49, 92, 82, 52],
       [94, 88, 86, 11, 28, 88, 33, 83, 99, 23],
       [16, 69, 59,  2, 45, 46, 35, 38, 94, 19],
       [79, 90, 36, 17, 80, 29, 93, 51, 44, 28]])

In [138]:
arr

array([0, 1, 2, 3, 4, 5])

In [139]:
arr.max()

5

In [140]:
arr.min()

0

In [141]:
arr.mean()

2.5

In [142]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
# 256 function in numpy

In [146]:
from numpy import *

a = np.array([1,2,3,4,5,8,9])
median(a)

4.0

In [125]:
arr

array([0, 1, 2, 3, 4, 5])

In [126]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [127]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [128]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [131]:
arr.reshape(3,2,order ='c')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [132]:
arr.reshape(2,3,order ='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [134]:
arr.reshape(2,3,order ='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [135]:
arr.reshape(2,3,order ='A') # A almost give c type

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [150]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [151]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [152]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Indexing

In [155]:
mat = np.arange(0,100).reshape(10,10)

In [156]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
row = 5
col = 6

In [159]:
row

5

In [160]:
col

6

In [162]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[row,col]

56

In [163]:
mat[4,5]

45

In [164]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
col = 6

In [167]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [168]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [172]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [173]:
row = 5

In [177]:
mat[row,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [180]:
row

5

In [182]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [183]:
mat[row:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[col:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [187]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [188]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
row = 5
col = 8

In [192]:
mat[:,col]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [193]:
mat[1,4]

14

In [194]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [195]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [196]:
mat[4:-2]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [197]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [203]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [207]:
mat[0:8]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [208]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[0:8:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [211]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [213]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [214]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [220]:
mat[-2::-2]

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [221]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [222]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [229]:
mat[2:6,2:4] # 2:6 indicate rows and 2:4 indicates col

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [230]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat[0,1] # , is used to extract specific elements

1

In [233]:
mat[1,6]

16

In [ ]:
mat

In [234]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [236]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [237]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
mat[2,6]

In [240]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[2:8,3:6]

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55],
       [63, 64, 65],
       [73, 74, 75]])

In [242]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[4,8]

48

In [245]:
mat[1:2,2:4]  #mat[row:col]

array([[12, 13]])

In [246]:
mat[3:4,3:4]

array([[33]])

In [247]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [248]:
mat[2:4,4:6]

array([[24, 25],
       [34, 35]])

# Masking
* Also known as filter

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
id(mat) # memory location address

1933441966192

In [251]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [253]:
mat < 50 # It will give True for the value lesser 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [254]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [255]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [256]:
mat[mat == 50]

array([50])

In [258]:
a1 = mat[mat < 50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [260]:
a2 = mat[mat <= 50]
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [262]:
a3 = mat[mat > 50]
a3

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [264]:
a4 = mat[mat >= 50]
a4

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [265]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [266]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [267]:
a3

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [268]:
a4

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])