# Statistics

In [1]:
import numpy as np

# Order statistics

### Q1. Return the minimum value of x along the second axis.

In [3]:
x = np.arange(4).reshape(2,2)
print("x:\n",x)
print("x_min\n",np.amin(x,1))

x:
 [[0 1]
 [2 3]]
x_min
 [0 2]


### Q2. Return the maximum value of x along the second axis. Reduce the second axis to the dimension with size one.

In [4]:
x = np.arange(4).reshape(2,2)
print("x:\n",x)
print("x_max\n",np.amax(x,1))

x:
 [[0 1]
 [2 3]]
x_max
 [1 3]


### Q3. Calcuate the difference between the maximum and the minimum of x along the second axis.

In [6]:
x = np.arange(10).reshape((2,5))
print("x:\n",x)
diff1 = np.ptp(x,1)
diff2 = np.amax(x,1) - np.min(x,1)
print(diff1)

x:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
[4 4]


### Q4. Compute the 75th percentile of x along the second axis.

In [7]:
x = np.arange(1,11).reshape((2,5))
print("x:\n",x)
print("75th percentile of x:",np.percentile(x,75,1))

x:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
75th percentile of x: [4. 9.]


# Averages and variances

### Q5. Compute the median of flattened x.

In [8]:
x = np.arange(1,10).reshape((3,3))
print("x:\n",x)

print("Median\n",np.median(x))

x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Median
 5.0


In [10]:
### Q6. Compute the weighted average of x.
x = np.arange(5)
weight = np.arange(1,6)
wght1 = np.average(x,weights = weight)
wght2 = (x*(weights/weights.sum())).sum()

print(wght1)
print(wght2)

2.6666666666666665
2.666666666666667
