# Sorting, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.5'

# Sorting

### Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
Sort = np.sort(x,axis = 1)
x.sort(axis = 1)

assert np.array_equal(Sort,x)

print(Sort)

[[1 4]
 [1 3]]


### Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surname = ('Kohli','sharma','Bumrah')
first_name = ('Virat','Rohit','Jasprit')

print(np.lexsort((first_name,surname)))

[2 0 1]


### Q3. Get the indices that would sort x along the second axis.

In [6]:
x = np.array([[1,4],[3,1]])
Sort = np.argsort(x,axis = 1)

print(Sort)

[[0 1]
 [1 0]]


### Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [11]:
x = np.random.permutation(10)
print("x:",x)
part = np.partition(x,5)

x.partition(5)

assert np.array_equal(x,part)
print(part)

x: [8 9 1 7 2 0 4 3 5 6]
[0 1 2 3 4 5 6 7 8 9]


### Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [16]:
x = np.random.permutation(10)
print("x:",x)

part = np.partition(x,3)
indices = np.argpartition(x,3)
print("partitioned",part)
print("Indices:",indices)


x: [7 6 1 5 8 9 4 0 2 3]
partitioned [0 1 2 3 4 5 6 7 8 9]
Indices: [7 2 8 9 6 3 1 0 4 5]


# Searching 

### Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [17]:
x = np.random.permutation(10).reshape(2,5)
print("x:",x)
print("Maximum value:",np.max(x,1))
print("Max indices:",np.argmax(x,1))

print("Minimum value",np.min(x,1))
print("Min indices:",np.argmin(x,1))

x: [[8 7 5 6 4]
 [0 3 2 1 9]]
Maximum value: [8 9]
Max indices: [0 4]
Minimum value [4 0]
Min indices: [4 0]


### Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.



In [18]:
x = np.array([[np.nan,4],[3,2]])
print("max_values ignoring NaNs :", np.nanmax(x,1))
print("max indices:",np.nanargmax(x,1))
print("min_values ignoring NaNs:",np.nanmin(x,1))
print("min_indices",np.nanargmin(x,1))

max_values ignoring NaNs : [4. 3.]
max indices: [1 0]
min_values ignoring NaNs: [4. 2.]
min_indices [1 1]


### Q8. Get the values and indices of the elements that are bigger than 2 in x.

In [19]:
x = np.array([[1,2,3],[1,3,5]])
print("Values bigger than 2:",x[x>2])
print("Indices:",np.nonzero(x>2))

Values bigger than 2: [3 3 5]
Indices: (array([0, 1, 1]), array([2, 1, 2]))


### Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [20]:
x = np.array([[1,2,3],[1,3,5]])
print(np.flatnonzero(x>2))


[2 4 5]


### Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [22]:
x = np.arange(-5,4).reshape(3,3)
print("x:",x)
print(np.where(x < 0,0,x))

x: [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[[0 0 0]
 [0 0 0]
 [1 2 3]]


### Q11. Get the indices where elements of y should be inserted to x to maintain order.


In [23]:
x = [1,3,5,7,9]
y = [0,4,2,6]
np.searchsorted(x,y)

array([0, 2, 1, 3])

# Counting 

### Q12. Get the number of nonzero elements in x.

In [29]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print(np.count_nonzero(x))
assert np.count_nonzero(x) == len(x[x!=0])

5
