# Array Manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'


**Q1.** Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [7]:
x = np.ones((10,10,3))
Reshape = np.reshape(x,[-1,150])
print(Reshape)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


**Q2.** Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [17]:
x = np.array([[1,2,3],[4,5,6]])
x1 = np.ravel(x,order = 'F')
print(x1)

[1 4 2 5 3 6]


**Q3.** Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [25]:
x = np.array([[1,2,3],[4,5,6]])
x1 = x.flat[4]
x2 = np.ravel(x)[4]
assert np.allclose(x1,x2)
print(x1)

5



**Q4.** Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).

In [37]:
x = np.zeros((3,4,5)) # 
x1  = np.swapaxes(x,1,0)


print(x1.shape)

(4, 3, 5)


In [38]:
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [39]:
x1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [34]:
x = np.zeros((3,4,5)) # 
x2 = x.transpose([1,0,2])
x2

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])


**Q5.** Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [43]:
x = np.zeros((3,4))
x1 = np.swapaxes(x,1,0)
print(x1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
x = np.zeros((3,4))
x2 = x.transpose([1,0])
print(x1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



**Q5.** Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [48]:
x = np.zeros((3,4))
x1 = np.expand_dims(x,axis = 1)
print(x1.shape)
print(x1)

(3, 1, 4)
[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]



**Q6.** Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [54]:
x = np.zeros((3,4,1))
x2 = np.squeeze(x)
x2.shape

(3, 4)


Q7. Lex x be an array

[[ 1 2 3]

[ 4 5 6].

and y be an array

[[ 7 8 9]

[10 11 12]].

Concatenate x and y so that a new array looks like

[[1, 2, 3, 7, 8, 9],

[4, 5, 6, 10, 11, 12]].



In [58]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
z = np.concatenate((x,y),1)
z

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [60]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
z1 = np.hstack((x,y))
z1

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])


Q8. Lex x be an array

[[ 1 2 3]
[ 4 5 6].

and y be an array

[[ 7 8 9]
[10 11 12]].

Concatenate x and y so that a new array looks like

[[ 1 2 3]
[ 4 5 6]
[ 7 8 9]
[10 11 12]]

In [62]:
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.array([[7,8,9],[10,11,12]])
z2 = np.concatenate((x,y),0)
print(z2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



**Q8.** Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [11]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])

z1 = np.column_stack((x,y))
z2 = np.vstack((x,y)).T
z3 = np.squeeze(np.dstack((x,y)))
print("Method 1:\n",z1)
print("Mthod 2:\n",z2)
print("Method 3:\n",z3)

Method 1:
 [[1 4]
 [2 5]
 [3 6]]
Mthod 2:
 [[1 4]
 [2 5]
 [3 6]]
Method 3:
 [[1 4]
 [2 5]
 [3 6]]



**Q9.** Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [13]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])

z = np.dstack((x,y))
z

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])


**Q10.** Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [16]:
x = np.arange(1,10)
a,b,c= np.split(x,[4,6])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


**Q11.** Let x be an array

[[[ 0., 1., 2., 3.],

[ 4., 5., 6., 7.]],

[[ 8., 9., 10., 11.],

[ 12., 13., 14., 15.]]].

Split it into two such that the first array looks like

[[[ 0., 1., 2.],

[ 4., 5., 6.]],

[[ 8., 9., 10.],

[ 12., 13., 14.]]].

and the second one look like:

[[[ 3.],

[ 7.]],

[[ 11.],

[ 15.]]].

In [30]:
x = np.arange(16).reshape(2,2,4)
z1 = np.split(x,[3],axis = 2)
print("Solution:\n",z1)

Solution:
 [array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


**Q12.** Let x be an array
[[ 0., 1., 2., 3.],

[ 4., 5., 6., 7.],

[ 8., 9., 10., 11.],

[ 12., 13., 14., 15.]].

Split it into two arrays along the second axis.

In [34]:
x = np.arange(0,16).reshape(2,2,4)
y = np.split(x,[2],axis = 2)
y

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [39]:
# Method 2:
x = np.arange(0,16).reshape(4,4)
y = np.split(x,[2],1)
y

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

**Q13.** Let x be an array
[[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.],
[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]].
Split it into two arrays along the first axis.

In [41]:
x = np.arange(0,16).reshape(4,4)
y = np.split(x,2,0)
y

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [45]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
x = np.arange(0,16).reshape(4,4)

y = np.vsplit(x,2)
y

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
x = np.arange(0,16).reshape(4,4)
y = np.hsplit(x,2)
y

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

**Q14.** Let x be an array [0, 1, 2]. Convert it to
[[0, 1, 2, 0, 1, 2],
[0, 1, 2, 0, 1, 2]].

In np.tile(A, reps), the parameter reps tells NumPy how many times to repeat the array A along each axis.



In [53]:
x = np.array([0,1,2])
y = np.tile(x,[2,2])
z = np.reshape(y,[2,6])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])


**Q15.** Let x be an array [0, 1, 2]. Convert it to
[0, 0, 1, 1, 2, 2].

In [59]:
x = np.array([0,1,2])
np.repeat(x,2)

array([0, 0, 1, 1, 2, 2])


**Q17.** Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.

In [62]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
y = np.unique(x,return_counts = True)
y

(array([1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2], dtype=int64))


**Q18.** Lex x be an array
[[ 1 2]
[ 3 4].
Flip x along the second axis.

In [65]:
x = np.array([[1,2],[3,4]])
y = np.flip(x,1)
y

array([[2, 1],
       [4, 3]])

**Q19.** Lex x be an array
[[ 1 2]
[ 3 4].
Flip x along the first axis.

In [66]:
x = np.array([[1,2],[3,4]])
y = np.flip(x,0)
y

array([[3, 4],
       [1, 2]])


**Q20.** Lex x be an array
[[ 1 2]
[ 3 4].
Rotate x 90 degrees counter-clockwise.

In [69]:
x = np.array([[1,2],[3,4]])
y = np.rot90(x)
y

array([[2, 4],
       [1, 3]])


**Q21** Lex x be an array
[[ 1 2 3 4]
[ 5 6 7 8].
Shift elements one step to right along the second axis.

In [72]:
x = np.arange(1,9).reshape([2,4])
np.roll(x,1,1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])