In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.3'

# Matrix and vector products

### Q1. Predict the results of the following code.

In [6]:
x = [1,2]
y = [[4,1],[2,2]]
print(np.dot(x,y))
print(np.dot(y,x))
print(np.matmul(x,y))
print(np.inner(x,y))
print(np.inner(y,x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


### Q2. Predict the results of the following code.

In [7]:
x = [[1,0],[0,1]]
y = [[4,1],[2,2],[1,1]]

print(np.dot(y,x))
print(np.matmul(y,x))

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


### Q3. Predict the results of the following code.

In [11]:
x = np.array([[1,4],[5,6]])
y = np.array([[4,1],[2,2]])

print(np.vdot(x,y))
print(np.vdot(y,x))
print(np.dot(x.flatten(),y.flatten()))
print(np.inner(x.flatten(),y.flatten()))
print((x * y).sum())

30
30
30
30
30


### Q4. Predict the results of the following code.

In [12]:
x = np.array(['a','b'],dtype = object)
y = np.array([1,2])

print(np.inner(x,y))
print(np.inner(y,x))
print(np.outer(x,y))
print(np.outer(y,x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


# Decompositions

### Q5. Get the lower-trianglular L in the Cholesky decomposition of x and verify it.



In [13]:
x = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]],dtype = np.int32)
L = np.linalg.cholesky(x)
print(L)

assert np.array_equal(np.dot(L,L.T.conjugate()),x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


### Q6. Compute the qr factorization of x and verify it.

In [15]:
x = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]],dtype = np.float32)
q,r = np.linalg.qr(x)
print("q = \n",q,"\nr=\n",r)
assert np.allclose(np.dot(q,r),x)

q = 
 [[-0.19611613 -0.16947544  0.9658243 ]
 [-0.5883484  -0.767624   -0.25416428]
 [ 0.78446454 -0.6180869   0.05083286]] 
r=
 [[-20.396078   -57.85426    105.31436   ]
 [  0.          -3.8580585  -24.853075  ]
 [  0.           0.           0.45749572]]


### Q7. Factor x by Singular Value Decomposition and verify it.

In [20]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x,full_matrices = False)
print("U=\n", U, "\ns=\n", s, "\nV=\n", V)
assert np.allclose(np.dot(U,np.dot(np.diag(s),V)),x)

U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.       2.236068 2.       0.      ] 
V=
 [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


# Matrix eigenvalues

### Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [21]:
x = np.diag((1,2,3))
eigenvals = np.linalg.eig(x)[0]
eigenvals_ = np.linalg.eigvals(x)
assert np.array_equal(eigenvals,eigenvals_)
print("eigenvalues are\n",eigenvals)

eigenvecs = np.linalg.eig(x)[1]
print("eigenvectors are\n",eigenvecs)

eigenvalues are
 [1. 2. 3.]
eigenvectors are
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q9. Predict the results of the following code.



In [23]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


# Norms and other numbers

### Q10. Calculate the Frobenius norm and the condition number of x.

In [24]:
x = np.arange(1,10).reshape((3,3))
print(np.linalg.norm(x,'fro'))
print(np.linalg.cond(x,'fro'))

16.881943016134134
3.193239515623568e+17


### Q11. Calculate the determinant of x.

In [27]:
x = np.arange(1,5).reshape((2,2))
det1 = np.linalg.det(x)
det2 = x[0,0] * x[1,1] - x[0,1] * x[1,0]

assert np.allclose(det1,det2)
print(det1)
print(det2)

-2.0000000000000004
-2


### Q12. Calculate the rank of x.

In [29]:
x = np.eye(4)
rank1 = np.linalg.matrix_rank(x)
rank2 = np.linalg.svd(x)[1].size

assert rank1 == rank2
print(rank1)
print(rank2)

4
4


### Q13. Compute the sign and natural logarithm of the determinant of x.

In [33]:
x = np.arange(1,5).reshape((2,2))
sign,logdet = np.linalg.slogdet(x)
det = np.linalg.det(x)
assert sign == np.sign(det)
assert logdet == np.log(np.abs(det))
print(sign,"\n",logdet)

-1.0 
 0.6931471805599455


### Q14. Return the sum along the diagonal of x.

In [35]:
x = np.eye(4)
diag1 = np.trace(x)
diag2 = x.diagonal().sum()

assert diag1 == diag2
print(diag1,"\n",diag2)

4.0 
 4.0


# Solving equations and inverting matrices

### Q15. Compute the inverse of x.

In [37]:
x = np.array([[1.,2.],[3.,4.]])
inv1 = np.linalg.inv(x)
assert np.allclose(np.dot(x,inv1),np.eye(2))
print(inv1)

[[-2.   1. ]
 [ 1.5 -0.5]]
