# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

# Trigonometric functions

### Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [4]:
x = np.array([0.,1.,30,90])
print("sine:",np.sin(x))
print("cosine",np.cos(x))
print("tangent",np.tan(x))

sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine [ 1.          0.54030231  0.15425145 -0.44807362]
tangent [ 0.          1.55740772 -6.4053312  -1.99520041]


### Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [6]:
x = np.array([-1.,0,1.])
print("inverse sine:",np.arcsin(x))
print("inverse cos:",np.arccos(x))
print("inverse tan:",np.arctan(x))

inverse sine: [-1.57079633  0.          1.57079633]
inverse cos: [3.14159265 1.57079633 0.        ]
inverse tan: [-0.78539816  0.          0.78539816]


### Q3. Convert angles from radians to degrees.

In [9]:
x = np.array([-np.pi,-np.pi/2,np.pi/2,np.pi])
print(x)

out1 = np.degrees(x)
out2 = np.rad2deg(x)

assert np.array_equal(out1,out2)
print(out1)
print(out2)

[-3.14159265 -1.57079633  1.57079633  3.14159265]
[-180.  -90.   90.  180.]
[-180.  -90.   90.  180.]


# Hyperbolic functions

### Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [10]:
x = np.array([-1.,0,1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


# Rounding

### Q6. Predict the results of these, paying attention to the difference among the family functions.

In [12]:
x = np.array([2.1,1.5,2.5,2.9,-2.1,-2.5,-2.9])
arnd = np.around(x)
Floor = np.floor(x)
Ciel = np.ceil(x)
Trunc = np.trunc(x)
rnd = [round(elem) for elem in x]

print(arnd)
print(Floor)
print(Ciel)
print(Trunc)
print(rnd)

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]
[2, 2, 2, 3, -2, -2, -3]


# Sums, products, differences

### Q8. Predict the results of these.

In [13]:
x = np.array(
    [[1,2,3,4],
     [5,6,7,8]]) 

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]

for out in outs:
    if out == "":
        print
    else:
        print("->",out)

-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]
-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]
-> [ 1  3  6 10 15 21 28 36]
-> [[ 1  2  3  4]
 [ 6  8 10 12]]
-> [[ 1  3  6 10]
 [ 5 11 18 26]]
-> [    1     2     6    24   120   720  5040 40320]
-> [[ 1  2  3  4]
 [ 5 12 21 32]]
-> [[   1    2    6   24]
 [   5   30  210 1680]]
-> 1
-> [1 2 3 4]
-> [[1]
 [5]]
-> 8
-> [5 6 7 8]
-> [[4]
 [8]]
-> 4.5
-> [3. 4. 5. 6.]
-> [[2.5]
 [6.5]]


C:\Users\suraj\AppData\Local\Temp\ipykernel_9724\4028741336.py:34: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if out == "":


### Q9. Calculate the difference between neighboring elements, element-wise.

In [14]:
x = np.array([1,2,4,7,0])
print(np.diff(x))

[ 1  2  3 -7]


### Q10. Calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[100] to it.

In [16]:
x = np.array([1,2,4,7,0])

out1 = np.ediff1d(x,to_begin=[0,0],to_end = [100])
out2 = np.insert(np.append(np.diff(x),100),0,[0,0])

assert np.array_equiv(out1,out2)
print(out1)
print(out2)

[  0   0   1   2   3  -7 100]
[  0   0   1   2   3  -7 100]


### Q11. Return the cross product of x and y.

In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.cross(x,y))

[-3  6 -3]


# Exponents and logarithms


### Q12. Compute e^x element-wise.

In [19]:
x = np.array([1.,2.,3.],np.float32)

exponent =  np.exp(x)
print(exponent)

[ 2.718282   7.3890557 20.085537 ]


### Q13. Calculate exp(x) - 1 for all elements in x.

In [20]:
x = np.array([1.,2.,3.],np.float32)

exp1 = np.expm1(x)
exp2 = np.exp(x) - 1

assert np.allclose(exp1,exp2)
print(exp1)
print(exp2)

[ 1.7182817  6.389056  19.085537 ]
[ 1.718282   6.3890557 19.085537 ]


### Q14. Calculate 2^p for all p in x.

In [22]:
x = np.array([1.,2.,3.],np.float32)
exp1 = np.exp2(x)
exp1 = 2 ** x

print(exp1)
print(exp2)

[2. 4. 8.]
[ 1.718282   6.3890557 19.085537 ]


###  Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [23]:
x = np.array([1,np.e,np.e**2])
print("Natural log:",np.log(x))
print("Common log:",np.log10(x))
print("base2 log:",np.log2(x))

Natural log: [0. 1. 2.]
Common log: [0.         0.43429448 0.86858896]
base2 log: [0.         1.44269504 2.88539008]


### Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

# Floating point routines

### 17. Return element-wise True where signbit is set.

In [24]:
x = np.array([-3,-2,-1,0,1,2,3])

out1 = np.signbit(x)
out2 = x < 0

assert np.array_equiv(out1,out2)
print(out1)
print(out2)

[ True  True  True False False False False]
[ True  True  True False False False False]


### Q18. Change the sign of x to that of y, element-wise.

In [27]:
x = np.array([-1,0,1])
y = -1.1

print(np.copysign(x,y))

[-1. -0. -1.]


# Arithmetic operations

### Q19. Add x and y element-wise.

In [28]:
x = np.array([1,2,3])
y = np.array([-1,-2,-3])

add1 = np.add(x,y)
add2 = x + y

assert np.array_equal(add1,add2)
print(add1)
print(add2)

[0 0 0]
[0 0 0]


### Q20. Subtract y from x element-wise.

In [29]:
x = np.array([3,4,5])
y = np.array(3)

sub1 = np.subtract(x,y)
sub2 = x - y

assert np.array_equal(sub1,sub2)
print(sub1)
print(sub2)

[0 1 2]
[0 1 2]


### Q21. Multiply x by y element-wise.

In [30]:
x = np.array([3,4,5])
y = np.array([1,0,-1])

mult1 = np.multiply(x,y)
mult2 = x * y

assert np.array_equal(mult1,mult2)
print(mult1)
print(mult2)

[ 3  0 -5]
[ 3  0 -5]


### Q22. Divide x by y element-wise in two different ways.

In [33]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])

div1 = np.divide(x,y)
div2 = x / y
assert np.array_equal(div1,div2)

div3 = np.floor_divide(x,y)
div4 = x // y
assert np.array_equal(div3,div4)

print(div1)
print(div2)
print("-------")
print(div3)
print(div4)

[3.         2.         1.66666667]
[3.         2.         1.66666667]
-------
[3. 2. 1.]
[3. 2. 1.]


### Q23. Compute numerical negative value of x, element-wise.

In [34]:
x = np.array([1,-1])

neg1 = np.negative(x)
neg2 = -x

assert np.array_equal(neg1,neg2)
print(neg1)

[-1  1]


### Q24. Compute the reciprocal of x, element-wise.

In [36]:
x = np.array([1.,2.,.2])
rec1 = np.reciprocal(x)
rec2 = 1/x

assert np.array_equal(rec1,rec2)
print(rec1)
print(rec2)

[1.  0.5 5. ]
[1.  0.5 5. ]


### Q25. Compute x^y, element-wise.

In [37]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

power = np.power(x,y)
print(power)

[[ 1  4]
 [ 3 16]]


### Q26. Compute the remainder of x / y element-wise in two different ways.

In [38]:
x = np.array([-3,-2,-1,1,2,3])
y = 2

rem1 = np.mod(x,y)
rem2 = x % y

assert np.array_equal(rem1,rem2)

print(rem1)
print(rem2)

[1 0 1 1 0 1]
[1 0 1 1 0 1]


# Miscellaneous

### Q27. If an element of x is smaller than 3, replace it with 3. And if an element of x is bigger than 7, replace it with 7.

In [40]:
x = np.arange(10)
repl1 = np.clip(x,3,7)
repl2 = np.copy(x)

repl2[repl2 < 3] = 3
repl2[repl2 > 7] = 7

assert np.array_equiv(repl1,repl2)
print(repl1)

[3 3 3 3 4 5 6 7 7 7]


### Q28. Compute the square of x, element-wise.

In [41]:
x = np.array([1,2,-1])
sqr1 = np.square(x)
sqr2 = x * x

assert np.array_equal(sqr1,sqr2)
print(sqr1)
print(sqr2)

[1 4 1]
[1 4 1]


### Q29. Coute square root of x element-wise.

In [42]:
x = np.array([1.,4.,9.])

sqrt1 = np.sqrt(x)
print(sqrt1)

[1. 2. 3.]


### Q30. Compute the absolute value of x.

In [43]:
x = np.array([[1,-1],[3,-3]])

abslt = np.abs(x)
print(abslt)

[[1 1]
 [3 3]]


### Q31. Compute an element-wise indication of the sign of x, element-wise.

In [45]:
x = np.array([1,3,0,-1,-3])

sign1 = np.sign(x)
sign2 = np.copy(x)
sign2[sign2 > 0] = 1
sign2[sign2 < 0] = -1

assert np.array_equal(sign1,sign2)
print(sign1)
print(sign2)

[ 1  1  0 -1 -1]
[ 1  1  0 -1 -1]
