# Set routines

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.5'

# Making Proper sets

### Q1. Get unique elements and reconstruction indices from x. And reconstruct x.

In [4]:
x = np.array([1,2,6,2,3,2])
uniq, indices = np.unique(x,return_inverse=True)
print("unique Elements:",uniq)
print("Reconstruction indices:",indices)
print("reconstructed:",uniq[indices])

unique Elements: [1 2 3 6]
Reconstruction indices: [0 1 3 1 2 1]
reconstructed: [1 2 6 2 3 2]


# Boolean operations

### Q2. Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [7]:
x = np.array([0,1,2,5,0])
y = np.array([0,1])
print(np.isin(x,y))

[ True  True False False  True]


### Q3. Find the unique intersection of x and y.

In [8]:
x = np.array([0,1,2,5,0])
y = np.array([0,1,4])

print(np.intersect1d(x,y))

[0 1]


### Q4. Find the unique elements of x that are not present in y.

In [9]:
x = np.array([0,1,2,5,0])
y = np.array([0,1,4])

print(np.setdiff1d(x,y))

[2 5]


### Q5. Find the xor elements of x and y.

In [11]:
x = np.array([0,1,2,5,0])
y = np.array([0,1,4])

mthd1 = np.setxor1d(x,y)
mthd2 = np.sort(np.concatenate((np.setdiff1d(x,y),np.setdiff1d(y,x))))
assert np.allclose(mthd1,mthd2)

print(mthd1)
print(mthd2)

[2 4 5]
[2 4 5]


### Q6. Find the union of x and y.

In [12]:
x = np.array([0,1,2,5,0])
y = np.array([0,1,4])

mthd1 = np.union1d(x,y)
mthd2 = np.sort(np.unique(np.concatenate((x,y))))
assert np.allclose(mthd1,mthd2)

print(mthd1)
print(mthd2)

[0 1 2 4 5]
[0 1 2 4 5]
