# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

In [3]:
author = "https://github.com/aniket20-99/Agentic_AI_Numpy"

# Simple random data

### Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [4]:
np.random.rand(3,2)

array([[0.92762757, 0.90945785],
       [0.85860622, 0.71807889],
       [0.12186453, 0.13096941]])

In [5]:
np.random.random((3,2))

array([[0.59428001, 0.1438881 ],
       [0.25933678, 0.78398373],
       [0.67260164, 0.64605866]])

### Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [7]:
arr1 = np.random.randn(1000,1000)
arr2 = np.random.standard_normal((1000,1000))
arr3 = np.random.normal(loc = 0.0,scale = 1.0,size = (1000,1000))

assert np.allclose(np.mean(arr1),np.mean(arr2),atol = 0.1)
assert np.allclose(np.mean(arr1),np.mean(arr3),atol = 0.1)
assert np.allclose(np.std(arr1),np.std(arr2),atol = 0.1)
assert np.allclose(np.std(arr1),np.std(arr2),atol = 0.1)

print(np.mean(arr3))
print(np.std(arr1))

-0.0013311060299470694
0.9997274446826393


### Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [8]:
np.random.randint(0,4,(3,2))

array([[3, 0],
       [2, 1],
       [1, 3]])

### Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [9]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [10]:
for i in range(10):
    print(np.random.choice(x,p = [.3,.5,.2]))

b'2 out of 10'
b'5 out of 10'
b'3 out of 10'
b'5 out of 10'
b'5 out of 10'
b'5 out of 10'
b'2 out of 10'
b'3 out of 10'
b'3 out of 10'
b'5 out of 10'


### Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [11]:
np.random.choice(10,3,replace = False)

array([9, 2, 3])

# Permutations

### Q6. Shuffle numbers between 0 and 9 (inclusive).

In [16]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

## or
print(np.random.permutation(10))


[8 2 3 4 7 9 1 0 6 5]
[5 6 7 4 3 8 9 2 0 1]


# Random generator

### Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [18]:
np.random.seed(10)