In [1]:
import numpy as np


In [2]:
np.__version__

'2.3.0'

In [3]:
list = [12,13,15,16,18,19,25]

In [4]:
arr = np.array(list)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[12 13 15 16 18 19 25]


In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [9]:
np.arange(20,10) # This will not work as the start is greater than the stop value

array([], dtype=int64)

In [10]:
np.arange(-10,10,3)

array([-10,  -7,  -4,  -1,   2,   5,   8])

In [11]:
np.arange(10,100,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [12]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((5,6),dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [14]:
a = np.ones((5,8),dtype = int)
print(a)
print(a.shape)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
(5, 8)


In [15]:
a = (5,6)
b = (6,5)

print(np.zeros(a))
print(np.ones(b))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [17]:
from numpy import * # Importing everything from numpy is not recommended as it can lead to confusion with variable names

In [18]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
range(10,30)

range(10, 30)

In [20]:
list(range(10))

TypeError: 'list' object is not callable

In [21]:
random.rand(5,2) 

array([[0.55525332, 0.44059901],
       [0.57911868, 0.28285602],
       [0.26020014, 0.82472822],
       [0.59656896, 0.45013431],
       [0.17769838, 0.72991705]])

In [22]:
np.random.rand(3,4,5)

array([[[0.55646094, 0.46723742, 0.49142099, 0.82373042, 0.79121134],
        [0.62059771, 0.40678091, 0.41533689, 0.05536145, 0.29108776],
        [0.27922463, 0.4314572 , 0.6305403 , 0.22206605, 0.20341863],
        [0.56473862, 0.19281686, 0.56594382, 0.10442017, 0.87606027]],

       [[0.55856117, 0.01750968, 0.76185712, 0.89440808, 0.80192762],
        [0.13281404, 0.52546781, 0.67545828, 0.92342365, 0.13501859],
        [0.57696582, 0.38072271, 0.53497145, 0.389363  , 0.74183124],
        [0.70781979, 0.22953495, 0.24846782, 0.91603574, 0.75427958]],

       [[0.78791277, 0.83651484, 0.09339457, 0.92900236, 0.27374734],
        [0.81988643, 0.0768282 , 0.50899735, 0.89501878, 0.02877741],
        [0.5437733 , 0.72451718, 0.14408526, 0.62048241, 0.76045519],
        [0.13193571, 0.27896916, 0.4886162 , 0.91931913, 0.3486821 ]]])

In [23]:
np.random.rand(5,4)

array([[0.84565169, 0.72304538, 0.75670684, 0.17912485],
       [0.06123498, 0.03169656, 0.73517239, 0.41705358],
       [0.71930214, 0.15345989, 0.70024367, 0.62723916],
       [0.34174292, 0.08392122, 0.61088319, 0.09173621],
       [0.99335751, 0.84938409, 0.1973485 , 0.31524536]])

In [24]:
np.random.randint(0,10)

4

In [25]:
np.random.randint(10,size = (3,5))

array([[4, 8, 4, 8, 1],
       [0, 5, 9, 5, 0],
       [4, 4, 2, 9, 7]], dtype=int32)

In [26]:
np.random.randint(0,20,20)

array([ 1, 11, 19,  3, 19,  0, 12,  7,  2, 14,  2,  4, 15,  2,  3,  2, 17,
        9, 18,  3], dtype=int32)

In [27]:
np.random.randint(0,20, size = (4,6))

array([[ 4, 13,  2,  6, 14, 16],
       [ 0, 13, 14, 16,  4,  1],
       [ 5,  6, 11,  4,  0, 10],
       [14, 13,  2,  4,  7, 13]], dtype=int32)

In [28]:
arr = np.random.randint(10,20,(5,5))

In [29]:
arr

array([[10, 18, 13, 18, 17],
       [14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18],
       [11, 17, 11, 10, 18],
       [14, 18, 19, 19, 14]], dtype=int32)

In [30]:
arr[0:]

array([[10, 18, 13, 18, 17],
       [14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18],
       [11, 17, 11, 10, 18],
       [14, 18, 19, 19, 14]], dtype=int32)

In [31]:
arr[1:]

array([[14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18],
       [11, 17, 11, 10, 18],
       [14, 18, 19, 19, 14]], dtype=int32)

In [32]:
arr[1:4]

array([[14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18],
       [11, 17, 11, 10, 18]], dtype=int32)

In [33]:
arr[1:4,2:4][1:2,1:]

array([[11]], dtype=int32)

In [34]:
arr

array([[10, 18, 13, 18, 17],
       [14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18],
       [11, 17, 11, 10, 18],
       [14, 18, 19, 19, 14]], dtype=int32)

In [35]:
arr[1,-1]

np.int32(14)

In [36]:
arr[0:-2]

array([[10, 18, 13, 18, 17],
       [14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18]], dtype=int32)

In [37]:
arr

array([[10, 18, 13, 18, 17],
       [14, 16, 13, 11, 14],
       [13, 12, 16, 11, 18],
       [11, 17, 11, 10, 18],
       [14, 18, 19, 19, 14]], dtype=int32)

In [38]:
arr[1:3,2:4]

array([[13, 11],
       [16, 11]], dtype=int32)

# Operations


In [39]:
a = np.random.randint(10,20,10)

In [40]:
a

array([16, 13, 13, 16, 13, 19, 12, 15, 14, 12], dtype=int32)

In [41]:
id(a)

2220262791696

In [42]:
id(arr)

2220263891824

In [43]:
b = np.random.randint(10,20,10)
b

array([12, 18, 14, 19, 12, 17, 11, 13, 10, 18], dtype=int32)

In [44]:
id(b)

2220262790640

In [45]:
c = np.random.randint(10,50,(10,10))
c

array([[23, 42, 17, 49, 15, 26, 21, 18, 35, 43],
       [31, 24, 20, 24, 49, 14, 15, 33, 37, 41],
       [48, 27, 26, 49, 15, 10, 28, 14, 29, 29],
       [30, 28, 39, 31, 24, 19, 11, 23, 35, 31],
       [19, 30, 49, 47, 46, 17, 23, 40, 15, 29],
       [30, 35, 42, 15, 15, 40, 38, 33, 49, 17],
       [42, 40, 29, 34, 44, 22, 11, 26, 12, 27],
       [37, 34, 24, 37, 49, 28, 11, 35, 29, 23],
       [40, 12, 32, 24, 27, 16, 20, 47, 28, 49],
       [49, 38, 35, 18, 35, 16, 20, 14, 11, 10]], dtype=int32)

In [46]:
c[2:7]

array([[48, 27, 26, 49, 15, 10, 28, 14, 29, 29],
       [30, 28, 39, 31, 24, 19, 11, 23, 35, 31],
       [19, 30, 49, 47, 46, 17, 23, 40, 15, 29],
       [30, 35, 42, 15, 15, 40, 38, 33, 49, 17],
       [42, 40, 29, 34, 44, 22, 11, 26, 12, 27]], dtype=int32)

In [47]:
c[2:8,3:8]

array([[49, 15, 10, 28, 14],
       [31, 24, 19, 11, 23],
       [47, 46, 17, 23, 40],
       [15, 15, 40, 38, 33],
       [34, 44, 22, 11, 26],
       [37, 49, 28, 11, 35]], dtype=int32)

In [48]:
c[::-1]

array([[49, 38, 35, 18, 35, 16, 20, 14, 11, 10],
       [40, 12, 32, 24, 27, 16, 20, 47, 28, 49],
       [37, 34, 24, 37, 49, 28, 11, 35, 29, 23],
       [42, 40, 29, 34, 44, 22, 11, 26, 12, 27],
       [30, 35, 42, 15, 15, 40, 38, 33, 49, 17],
       [19, 30, 49, 47, 46, 17, 23, 40, 15, 29],
       [30, 28, 39, 31, 24, 19, 11, 23, 35, 31],
       [48, 27, 26, 49, 15, 10, 28, 14, 29, 29],
       [31, 24, 20, 24, 49, 14, 15, 33, 37, 41],
       [23, 42, 17, 49, 15, 26, 21, 18, 35, 43]], dtype=int32)

In [49]:
c[:-1,:-1]

array([[23, 42, 17, 49, 15, 26, 21, 18, 35],
       [31, 24, 20, 24, 49, 14, 15, 33, 37],
       [48, 27, 26, 49, 15, 10, 28, 14, 29],
       [30, 28, 39, 31, 24, 19, 11, 23, 35],
       [19, 30, 49, 47, 46, 17, 23, 40, 15],
       [30, 35, 42, 15, 15, 40, 38, 33, 49],
       [42, 40, 29, 34, 44, 22, 11, 26, 12],
       [37, 34, 24, 37, 49, 28, 11, 35, 29],
       [40, 12, 32, 24, 27, 16, 20, 47, 28]], dtype=int32)

In [50]:
c.max()

np.int32(49)

In [51]:
c.min()

np.int32(10)

In [52]:
c.mean()

np.float64(28.87)

In [53]:
from numpy import *

In [54]:
c.mean()

np.float64(28.87)

In [55]:
median(a)

np.float64(13.5)

In [56]:
c.shape

(10, 10)

In [57]:
c.reshape(20,5)

array([[23, 42, 17, 49, 15],
       [26, 21, 18, 35, 43],
       [31, 24, 20, 24, 49],
       [14, 15, 33, 37, 41],
       [48, 27, 26, 49, 15],
       [10, 28, 14, 29, 29],
       [30, 28, 39, 31, 24],
       [19, 11, 23, 35, 31],
       [19, 30, 49, 47, 46],
       [17, 23, 40, 15, 29],
       [30, 35, 42, 15, 15],
       [40, 38, 33, 49, 17],
       [42, 40, 29, 34, 44],
       [22, 11, 26, 12, 27],
       [37, 34, 24, 37, 49],
       [28, 11, 35, 29, 23],
       [40, 12, 32, 24, 27],
       [16, 20, 47, 28, 49],
       [49, 38, 35, 18, 35],
       [16, 20, 14, 11, 10]], dtype=int32)

In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
median(arr)

np.float64(6.5)

In [59]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [62]:
arr.reshape(2,6,order = 'c')

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [63]:
arr.reshape(4,3,order = 'f')

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [64]:
arr.reshape(3,4,order = 'a')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# indexing


In [65]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
row = 5
col = 6

In [67]:
mat[row,col]

np.int64(56)

In [68]:
mat[8,7]

np.int64(87)

In [69]:
mat[1:5,2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

In [70]:
row = 5
col = 7

In [71]:
mat[:,col]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [72]:
mat[row:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
mat[2,8]

np.int64(28)

In [74]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
mat[0,1]

np.int64(1)

In [76]:
mat[0:5:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaping = np.reshape(arr,(4,3))
print("Reshaped Array:\n",reshaping)

Reshaped Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [85]:
f1 = np.array([[1,2,3,4],[5,6,7,8]])
flattend = np.ravel(f1)
print(flattend)

[1 2 3 4 5 6 7 8]


In [86]:
T = np.array([[10,20],[30,40],[50,60],[70,80]])
transpose = np.transpose(T)
print(T)
print(transpose)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 30 50 70]
 [20 40 60 80]]


In [89]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

stacked = np.vstack([a1,a2])
print(f"Vertical stacked:\n{stacked}")

Vertical stacked:
[[1 2 3 4]
 [5 6 7 8]]


In [92]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

stacked = np.hstack([a1,a2])
print(f"Horizontal stacked {stacked}")

Horizontal stacked [1 2 3 4 5 6 7 8]


In [93]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])
add = np.add(a1,a2)
print(add)

[ 6  8 10 12 14]


In [94]:
a1 = np.array([5,10,20,34,49])
added = np.add(a1,10)
print(added)

[15 20 30 44 59]


In [98]:
a = np.array([1,2,3,4,5])
sqr = np.power(a,2)
print(sqr)

[ 1  4  9 16 25]


In [101]:
a = np.array([16,25,36,49,64])

sqrt1 = np.sqrt()
print(sqrt1)

TypeError: No loop matching the specified signature and casting was found for ufunc sqrt

In [102]:
a = np.array([16,25,36,49,64])

dot_prdt = np.dot(a,a1)
print(dot_prdt)

5852


In [103]:
a = np.array([16,25,36,49,64])
mean1 = np.mean(a)

print(mean1)

38.0


In [104]:
median1 = np.median(a)
print(median1)

36.0


In [106]:
std_dv = np.std(a)
print(std_dv)

17.052858997833766


In [109]:
Min = np.min(a)
print(Min)

16


In [111]:
mat = np.array([[2,5],[4,6]])

In [112]:
detr = np.linalg.det(mat)
print(detr)

-7.999999999999998


In [114]:
inverse = np.linalg.inv(mat)
print(inverse)

[[-0.75   0.625]
 [ 0.5   -0.25 ]]


In [115]:
rand_var = np.random.rand(3)
print(rand_var)

[0.8865554  0.27310957 0.91257442]


In [118]:
np.random.seed(0)
rand_var = np.random.rand(5)
print(rand_var)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [120]:
rand_int = np.random.randint(0,10,size = 10)
print(rand_int)

[7 8 1 5 9 8 9 4 3 0]


In [123]:
np.random.seed(0)
rand_int = np.random.randint(0,10,size = 10)
print(rand_int)

[5 0 3 3 7 9 3 5 2 4]


In [125]:
logical_test = np.array([True,False,True,False])
all_true = np.all(logical_test)
print(all_true)

False
